# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_management', '0002_profileinfo_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.BooleanField(default=False)),
                ('anemia', models.BooleanField(default=False)),
                ('arthritis', models.BooleanField(default=False)),
                ('chickenpox', models.BooleanField(default=False)),
                ('coxsackie', models.BooleanField(default=False)),
                ('diphtheria', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('frequentColds', models.BooleanField(default=False)),
                ('germanMeasles', models.BooleanField(default=False)),
                ('highBloodPressure', models.BooleanField(default=False)),
                ('influenza', models.BooleanField(default=False)),
                ('kidneyDisease', models.BooleanField(default=False)),
                ('measles', models.BooleanField(default=False)),
                ('migraines', models.BooleanField(default=False)),
                ('mumps', models.BooleanField(default=False)),
                ('obesity', models.BooleanField(default=False)),
                ('pneumonia', models.BooleanField(default=False)),
                ('polio', models.BooleanField(default=False)),
                ('rheumaticFever', models.BooleanField(default=False)),
                ('scarlatina', models.BooleanField(default=False)),
                ('scarletFever', models.BooleanField(default=False)),
                ('strokes', models.BooleanField(default=False)),
                ('syphilis', models.BooleanField(default=False)),
                ('tonsillitis', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('whoopingCough', models.BooleanField(default=False)),
                ('otherText', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('released', models.BooleanField(default=False)),
                ('dateIssued', models.DateField()),
                ('result', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_management.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200, null=True)),
                ('profileInfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.ProfileInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.Doctor')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.Hospital')),
                ('medicalInfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.MedicalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationCategory', models.CharField(max_length=200)),
                ('medication', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('directions', models.TextField(max_length=200)),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.Prescription'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profileInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.ProfileInfo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='userInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.UserInfo'),
        ),
    ]
