# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0004_z_adamantane_antivirals_z_adrenal_cortical_steroids_z_adrenal_corticosteroid_inhibitors_z_adrenergic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
